[build]
target = "aarch64-aos.json"

[unstable]
build-std = ["core"]

[target.aarch64-aos]
linker = "rust-lld"
rustflags = ["-C", "link-arg=-flavor", "-C", "link-arg=ld", "-C", "link-arg=-T", "-C", "link-arg=link.ld"]
